# Generated by Django 5.1.4 on 2025-01-31 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamientos', '0003_remove_estacionamiento_lat_and_more'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='fechaPago',
            new_name='fecha_pago',
        ),
        migrations.AddField(
            model_name='pago',
            name='transaccion_id',
            field=models.CharField(blank=True, default='sin_transaccion', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Fallido', 'Fallido')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estacionamientos.reserva'),
        ),
    ]
